#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BATTERYSCRIPT,
	BULLETSCRIPT,
	CAMERAMOVESCRIPT,
	CAMERAZOOMSCRIPT,
	CEILINGSCRIPT,
	DESCENDABLEFLOORSCRIPT,
	DOORSCRIPT,
	EFFECTSCRIPT,
	GRAVITYSCRIPT,
	GRENADESCRIPT,
	HEADHUNTERSCRIPT,
	JUMPWALLSCRIPT,
	MAINCAMERASCRIPT,
	MINESCRIPT,
	MISSILESCRIPT,
	MONSTERATTACKRANGESCRIPT,
	MONSTERATTACKSCRIPT,
	MONSTERCOPSCRIPT,
	MONSTERGRUNTSCRIPT,
	MONSTERPOMPSCRIPT,
	MONSTERRAYSCRIPT,
	MONSTERSCRIPT,
	MOUSESCRIPT,
	NEXTLEVELSCRIPT,
	NORMALFLOORSCRIPT,
	NORMALWALLSCRIPT,
	PLAYERATTACKSCRIPT,
	PLAYERSCRIPT,
	RIFLESCRIPT,
	STAIRSCRIPT,
	STARTMENUSCRIPT,
	TIMERSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
